### PR TITLE
Cutting order optimization

### PR DESCRIPTION
**Pull request by Biondilbiondo**
Added a function in simple cam to optimize the cutting order of the lines to get a much shorter gcode.

### CODE REVIEW

**Comment by ghost** [comment]
@lautr3k @cprezzi

**Comment by cprezzi** [comment]
Reversing the cut Direction is OK for laser cutting but causes Problems when milling. (Not sure if simple Cam is used for milling)

**Comment by Biondilbiondo** [comment]
I have supposed simple cam is just for laser cutting: when I create gcodes for milling machine i want a more advanced control on what the gcode is supposed to do. Anyway I don't understend what could go wrong in inverting cutting direction (with rispect to how a line is drown in the the CAD) during milling.

**Comment by cprezzi** [comment]
It's a big difference in surface quality and tool wearing if you do conventional up milling or down milling (climb milling)
grafik
In every CAM you can select the direction.

**Comment by ghost** [comment]
We have a pretty decent CAM in LW4.

While I do appreciate a G0 optimisation (speak to @tbfleming though)  i
dont really think we need to enhance lw3's much,  since LW4 is nearly done
anyway

**Pull request closed without merging**
