### PR TITLE
Emblaser videosources

### PR DESCRIPTION
**Pull request by copet80**

### CODE REVIEW

**Comment by ghost** [comment]
As a sidenote,  how much of the emblaser branch can make its way to master?

**Comment by krolco** [comment]
Some of it, but it will require a bit of care: right now it only works as an app, requires python (because the app packager requires that), and has a few emblaser-specific features in-dev. For changes that aren't emblaser-specific, I have been doing them on master and merging them to emblaser so that master benefits also.

**Comment by ghost** [comment]
Ok cool (: now i am happy since i know the plan there.  Keep up the way you
do then (:

**Comment by krolco** [comment]
I think pretty much everyone except Anthony and I should be working on master; I don't think anybody else is working on emblaser-specific stuff. I didn't look into the camera stuff yet; that might be a good candidate for a merge back to master.

**Comment by ghost** [comment]
The packaged app might be useful too.  But we need to start thinking if
that works for packing LaserWeb4 too.  I see @tbfleming is making amazingly
fast progress on that

**Pull request merged**
