### PR TITLE
Emblaser electron

### PR DESCRIPTION
**Pull request by jmmstm**

### CODE REVIEW

**Comment by ghost** [comment]
@darklylabs @jmmstm awesome, care to elaborate a little?  I am on the road last two days of holiday,  hard to review via mobile,  but anxious to hear how it went

**Comment by krolco** [comment]
It looks like most of this are my commits to the emblaser-branch in the pull request. Anthony, did you intend to pull everything from that branch into Master? If not, you may need to make a smaller branch with just a few cherry-picked commits.

**Comment by anthonytvamp** [comment]
There are some of my commits that touches LaserWeb codes, but majority of it are wrapper and configuration. I intended to create a pull request from the emblaser-electron to the emblaser branches. You could scrap my changes in the conflicting index.html file, and I'll redo them after I pull changes from master to my branch. What is the best way to go from here?

**Comment by krolco** [comment]
I can try to help with this in a couple of hours. It looks your pull request just had the wrong targets. You might want a different structure to work with here -- we can discuss this later also.

**Comment by copet80** [comment]
Oh let me check tonight. Which wrong targets if you can let me know in
advance?

**Comment by krolco** [comment]
Timezones are hard. :) 

You said you wanted to create a pull request from emblaser-electron to emblaser. This pull request is emblaser-electron to master. On the pull request screen, the "left side" should say emblaser (the base branch) and the "right side" should say "emblaser-electron".

I made a pull request (#154) that had those settings and merged it, so you should be good to go now. I'm going to close this request. Thank you for your work!

**Comment by cojarbi** [comment]
I would gladly like to test this installer on Mac. Is it working yet? How do you create or run it?

**Pull request closed without merging**
