### PR TITLE
Fixes Raster feedrate calc

### PR DESCRIPTION
**Pull request by cojarbi**

### CODE REVIEW

**Comment by ghost** [comment]
The title of the pull says 'fixed raster calc'  but the pull only contains
a readme update?

**Comment by cojarbi** [comment]
Yeah it doesn't seem correct to me either. Do git permit to pull the same twice? Because the Readme is the one I sent a couple of days ago and this one was from today

**Comment by ghost** [comment]
Yip,  it can mix up.  Create a branch, do fixes,  submit pull,  merge,
delete your branch.   Works best for beginners.  Branch per pull...

**Comment by ghost** [comment]
Or skip the pull,  you have push rights to the main repo

**Comment by cojarbi** [comment]
Dosent seem to have push access

**Pull request merged**
