### PR TITLE
Fixed SVGReader.js to be callable as a library from outside a browser

### PR DESCRIPTION
**Pull request by tritao**
This PR allows the SVG reading library to be called from a Node.js environment.

The idea behind this is that I want to use parts of LaserWeb3 as a library from Node and the first parts I'm trying to isolate are the SVG to G-Code and cost-estimation bits.

Is that direction (making code a bit more modular, allowed to use as library) something that would of interest to push to the main repository?

### CODE REVIEW

**Comment by ghost** [comment]
Absolutely welcome!  Just speak to @lautr3k as well, since he is busy modularising things too. 

I love node, so making things work in it, is great.  I am clueless sadly, so can't do it without all your help (:

I tried getting LW onto NPM too since it would making installing laserweb easier https://www.npmjs.com/package/laserweb   but thats not working :(

**Comment by ghost** [comment]
https://github.com/openhardwarecoza/LaserWeb3/issues/99

**Comment by tritao** [comment]
Great to hear. I'll be happy to contribute to those efforts.

@lautr3k What are you working on / current thoughts?

Personally I think one of the big problems in the current codebase is the dependency on global state in some parts. It would be really nice to move to a module system like ES6/ES2015. That'd force us to declare the dependencies for each file and allow re-use in a much simpler way by compiling code to either browser or Node environments.

**Comment by ghost** [comment]
@tritao @openhardwarecoza Sorry for the lack of communication... 
Better than words , some code : https://github.com/openhardwarecoza/LaserWeb4/tree/dev
Waiting for your comments.

**Comment by tritao** [comment]
@lautr3k No problem.

I've been doing some experiments myself over the weekend, tried to modularize the existing LaserWeb3 codebase but gave up, it's too hard to do it without rewriting pretty much the entire code.

I am checking out the new code you linked. I like it, it's a much cleaner approach than existing architecture. I'm making some changes to present some ideas from my previous post, basically using newer JavaScript features that I think make the code easier and shorter.

I hope to have something to show soon so you guys can check it out. Let's move discussion to LaserWeb4 issue so more people can find it.

**Comment by ghost** [comment]
ES6/ES2015 is not yet a well supported standard, I do not think it is appropriate for this kind of project. And to be honest I am not at all comfortable with it. But I look forward to seeing what you will offer and feel free to open an issue on the LaserWeb4 repo.

**Comment by arthurwolf** [comment]
Laserweb really needs more contributors, and using newer JS features is going to be doing the opposite : frighten them away. The code really should use "classic" JS for now, it'll always be time to move to something better later on when it's less important for the code to look friendly.

**Pull request merged**
