### PR TITLE
Fixed from mm/m to mm/s on convert tab & default feed rate.

### PR DESCRIPTION
**Pull request by magicsmoke**
Noticed it was still showing mm/m on the convert tab, and was wondering why my engraver tried to do 192000mm/m speeds. Turns out I didn't notice you changed to mm/s instead of the standard mm/m...

### CODE REVIEW

**Comment by ghost** [comment]
@cojarbi someone beat you to it

**Comment by cojarbi** [comment]
Thank god

**Comment by magicsmoke** [comment]
Why the change though

**Comment by ghost** [comment]
Lol,  no,  thank Daniel!

**Comment by cojarbi** [comment]
Thanka Daniel. Does this fixes the actual speed interpretation?

**Pull request merged**
