### PR TITLE
Small error

### PR DESCRIPTION
**Pull request by sonex128**
I believe this is an error.  I assume it should be Dark instead of Light.

### CODE REVIEW

**Comment by ghost** [comment]
FeedrateW = white = lighter side of shade (i.e maximum speed at which it is
still not burning.  After that point 5% for example,  should already begin
shading the material...)

**Comment by sonex128** [comment]
This is what I was trying to fix.  The first commit I had it backwards.  Before I changed it they both said Light mm/s.

**Comment by ghost** [comment]
I changed it to this:  (Only showing mm/s once helps declutter a little)

darklight

**Comment by sonex128** [comment]
Thanks.  Looks better.

**Pull request closed without merging**
