### PR TITLE
Merge Electron + Emblaser Enhancements back to Master

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@krolco @cprezzi 

We need to get Emblaser into Master ASAP

Right now its mergable. But i'll hold off on an OK from you before I do! (Also try not to break the merge by pushing other stuff to Master before this is merged - Emblaser is about to start shipping so the electron branch is becoming critical. 

If we merge this into master, we can use the same branch both as "run from node" and as "use to build electron distributables"

**Comment by cprezzi** [comment]
Let me test emblaser branch before we merge. I'll get back asap.

**Comment by cprezzi** [comment]
Nope, doesn't work. Needs an npm install which crashes on installing dependencies.

**Comment by ghost** [comment]
On which dependency?  Ran though fine on my machine.  Might need a npm
install -g windows-build-tools

**Comment by ghost** [comment]
Did another test from clean

```
dev@dev-PC MINGW64 ~/Documents/Github
$ rm -rf LaserWeb3/

dev@dev-PC MINGW64 ~/Documents/Github
$ clear

dev@dev-PC MINGW64 ~/Documents/Github
$ git clone https://github.com/LaserWeb/LaserWeb3.git
Cloning into 'LaserWeb3'...
remote: Counting objects: 6970, done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 6970 (delta 23), reused 4 (delta 4), pack-reused 6884
Receiving objects: 100% (6970/6970), 11.63 MiB | 711.00 KiB/s, done.
Resolving deltas: 100% (3673/3673), done.

dev@dev-PC MINGW64 ~/Documents/Github
$ cd LaserWeb3/

dev@dev-PC MINGW64 ~/Documents/Github/LaserWeb3 (master)
$ git branch -r
  origin/HEAD -> origin/master
  origin/JohnS-Dev
  origin/emblaser
  origin/emblaser-electron
  origin/marlin-comm
  origin/master
  origin/optimization
  origin/overrides

dev@dev-PC MINGW64 ~/Documents/Github/LaserWeb3 (master)
$ git fetch origin emblaser
From https://github.com/LaserWeb/LaserWeb3
 * branch            emblaser   -> FETCH_HEAD

dev@dev-PC MINGW64 ~/Documents/Github/LaserWeb3 (master)
$ git checkout emblaser
Branch emblaser set up to track remote branch emblaser from origin.
Switched to a new branch 'emblaser'

dev@dev-PC MINGW64 ~/Documents/Github/LaserWeb3 (emblaser)
$ npm start

> laserweb@3.254.0 start C:\Users\dev\Documents\Github\LaserWeb3
> npm install && npm run copy && electron ./app

npm WARN optional dep failed, continuing 7zip-bin-mac@1.0.1
npm WARN optional dep failed, continuing 7zip-bin-linux@1.0.3

> electron@1.4.1 postinstall C:\Users\dev\Documents\Github\LaserWeb3\node_modules\electron
> node install.js


> serialport@4.0.6 install C:\Users\dev\Documents\Github\LaserWeb3\node_modules\serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "C:\Users\dev\Documents\Github\LaserWeb3\node_modules\serialport\build\Release\serialport.node" is installed via remote

> serialport@2.1.2 install C:\Users\dev\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "C:\Users\dev\Documents\Github\LaserWeb3\node_modules\tinyg\node_modules\serialport\build\Release\serialport.node" is installed via remote

> laserweb@3.254.0 postinstall C:\Users\dev\Documents\Github\LaserWeb3
> install-app-deps

Installing app dependencies for arch x64 to C:\Users\dev\Documents\Github\LaserWeb3\app
dotenv@2.0.0 node_modules\dotenv

ncp@2.0.0 node_modules\ncp

chalk@1.1.3 node_modules\chalk
├── supports-color@2.0.0
├── ansi-styles@2.2.1
├── escape-string-regexp@1.0.5
├── strip-ansi@3.0.1 (ansi-regex@2.0.0)
└── has-ansi@2.0.0 (ansi-regex@2.0.0)

node-static@0.7.9 node_modules\node-static
├── mime@1.3.4
├── colors@1.1.2
└── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)

copyfiles@1.0.0 node_modules\copyfiles
├── ltcdr@2.2.1
├── mkdirp@0.5.1 (minimist@0.0.8)
├── noms@0.0.0 (inherits@2.0.3, readable-stream@1.0.34)
├── through2@2.0.3 (xtend@4.0.1, readable-stream@2.2.2)
└── glob@7.1.1 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6, minimatch@3.0.3)

socket.io@1.7.1 node_modules\socket.io
├── object-assign@4.1.0
├── socket.io-adapter@0.5.0
├── has-binary@0.1.7 (isarray@0.0.1)
├── debug@2.3.3 (ms@0.7.2)
├── socket.io-parser@2.3.1 (isarray@0.0.1, json3@3.3.2, component-emitter@1.1.2, debug@2.2.0)
├── engine.io@1.8.1 (base64id@0.1.0, cookie@0.3.1, accepts@1.3.3, ws@1.1.1, engine.io-parser@1.3.1)
└── socket.io-client@1.7.1 (to-array@0.1.4, component-emitter@1.2.1, indexof@0.0.1, component-bind@1.0.0, object-component@0.0.3, backo2@1.0.2, parseuri@0.0.5, engine.io-client@1.8.1)

request@2.79.0 node_modules\request
├── aws-sign2@0.6.0
├── oauth-sign@0.8.2
├── tunnel-agent@0.4.3
├── forever-agent@0.6.1
├── is-typedarray@1.0.0
├── caseless@0.11.0
├── stringstream@0.0.5
├── isstream@0.1.2
├── aws4@1.5.0
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── uuid@3.0.1
├── qs@6.3.0
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── mime-types@2.1.13 (mime-db@1.25.0)
├── tough-cookie@2.3.2 (punycode@1.4.1)
├── form-data@2.1.2 (asynckit@0.4.0)
├── hawk@3.1.3 (cryptiles@2.0.5, boom@2.10.1, sntp@1.0.9, hoek@2.16.3)
├── http-signature@1.1.1 (assert-plus@0.2.0, jsprim@1.3.1, sshpk@1.10.1)
└── har-validator@2.0.6 (pinkie-promise@2.0.1, commander@2.9.0, is-my-json-valid@2.15.0)

electron@1.4.1 node_modules\electron
├── extract-zip@1.5.0 (debug@0.7.4, yauzl@2.4.1, mkdirp@0.5.0, concat-stream@1.5.0)
└── electron-download@3.0.1 (home-path@1.0.3, semver@5.3.0, minimist@1.2.0, debug@2.3.3, rc@1.1.6, path-exists@2.1.0, sumchecker@1.2.0, fs-extra@0.30.0, nugget@2.0.1)

electron-builder@10.2.0 node_modules\electron-builder
├── tunnel-agent@0.4.3
├── ini@1.3.4
├── isbinaryfile@3.0.1
├── chromium-pickle-js@0.2.0
├── ansi-escapes@1.4.0
├── hosted-git-info@2.1.5
├── progress@1.1.8
├── stat-mode@0.2.2
├── semver@5.3.0
├── mime@1.3.4
├── lodash.template@4.4.0 (lodash.templatesettings@4.1.0, lodash._reinterpolate@3.0.0)
├── is-ci@1.0.10 (ci-info@1.0.0)
├── debug@2.3.3 (ms@0.7.2)
├── node-emoji@1.4.1 (string.prototype.codepointat@0.2.0)
├── parse-color@1.0.0 (color-convert@0.5.3)
├── minimatch@3.0.3 (brace-expansion@1.1.6)
├── pretty-ms@2.1.0 (plur@1.0.0, parse-ms@1.0.1, is-finite@1.0.2)
├── cli-cursor@1.0.2 (restore-cursor@1.0.1)
├── uuid-1345@0.99.6 (macaddress@0.2.8)
├── 7zip-bin@2.0.4 (7zip-bin-win@2.0.2)
├── source-map-support@0.4.6 (source-map@0.5.6)
├── sanitize-filename@1.6.1 (truncate-utf8-bytes@1.0.2)
├── cuint@0.2.2
├── plist@2.0.1 (base64-js@1.1.2, xmldom@0.1.27, xmlbuilder@8.2.2)
├── bluebird-lst-c@1.0.5 (bluebird@3.4.6)
├── fs-extra-p@3.0.3 (fs-extra@1.0.0)
├── progress-stream@1.2.0 (speedometer@0.1.4, through2@0.2.3)
├── asar-electron-builder@0.13.5 (commander@2.9.0, mkdirp@0.5.1)
├── normalize-package-data@2.3.5 (is-builtin-module@1.0.0, validate-npm-package-license@3.0.1)
├── electron-macos-sign@1.3.4 (compare-version@0.1.2, minimist@1.2.0, bluebird@3.4.6)
├── read-installed@4.0.3 (debuglog@1.0.1, util-extend@1.0.3, graceful-fs@4.1.11, slide@1.1.6, readdir-scoped-modules@1.0.2, read-package-json@2.0.4)
├── update-notifier@1.0.2 (is-npm@1.0.0, semver-diff@2.1.0, lazy-req@1.1.0, xdg-basedir@2.0.0, boxen@0.6.0, configstore@2.1.0, latest-version@2.0.0)
├── js-yaml@3.7.0 (esprima@2.7.3, argparse@1.0.9)
├── yargs@6.4.0 (get-caller-file@1.0.2, decamelize@1.2.0, camelcase@3.0.0, y18n@3.2.1, which-module@1.0.0, set-blocking@2.0.0, yargs-parser@4.1.0, require-directory@2.1.1, require-main-filename@1.0.1, window-size@0.2.0, string-width@1.0.2, cliui@3.2.0, os-locale@1.4.0, read-pkg-up@1.0.1)
├── electron-download-tf@3.1.0 (path-exists@3.0.0, minimist@1.2.0, rc@1.1.6, sumchecker@1.2.0, fs-extra@1.0.0, nugget@2.0.1)
├── archiver@1.2.0 (buffer-crc32@0.2.13, readable-stream@2.2.2, glob@7.1.1, zip-stream@1.1.0, tar-stream@1.5.2, async@2.1.4, lodash@4.17.2)
└── archiver-utils@1.3.0 (normalize-path@2.0.1, graceful-fs@4.1.11, lazystream@1.0.0, readable-stream@2.2.2, glob@7.1.1, lodash@4.17.2)

serialport@4.0.6 node_modules\serialport
├── bindings@1.2.1
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── debug@2.3.3 (ms@0.7.2)
├── nan@2.4.0
├── lie@3.1.0 (immediate@3.0.6)
└── object.assign@4.0.4 (object-keys@1.0.11, function-bind@1.1.0, define-properties@1.1.2)

tinyg@0.4.5 node_modules\tinyg
├── sprintf@0.1.5
├── q@1.4.1
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.5, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── nomnom@1.8.1 (underscore@1.6.0, chalk@0.4.0)
└── serialport@2.1.2 (bindings@1.2.1, sf@0.1.7, object.assign@4.0.4, nan@2.2.1, optimist@0.6.1, bluebird@3.4.6)

> laserweb@3.254.0 copy C:\Users\dev\Documents\Github\LaserWeb3
> copyfiles *.js app && ncp public app/public --limit=6



***************************************************************
                 ---- LaserWeb Started ----
***************************************************************
  Access the LaserWeb User Interface:
  1. Open Chrome
  2. Go to :   http://192.168.43.191:8000/
***************************************************************


* Updates:
  Remember to check the commit log on
  https://github.com/openhardwarecoza/LaserWeb3/commits/master
  regularly, to know about updates and fixes, and then when ready
  update LaserWeb3 accordingly by running git pull

* Support:
  If you need help / support, come over to
  https://plus.google.com/communities/115879488566665599508

```

**Comment by ghost** [comment]
app

Compiled app, talking to a Smoothieboard (Yeah, probably the only person in the world to bring a Smoothie along all road trips)

**Comment by ghost** [comment]
Exe version to test https://drive.google.com/file/d/0B-UxBll2MapjQlphVFlnMU5XRjQ/view?usp=sharing

**Comment by funinthefalls** [comment]
Install exe worked great for me under Win 10 on a 64 bit 6 core AMD box

**Comment by cprezzi** [comment]
I have done what one of our users would do:

- git pull
- node start-grbl.js -> errors
- npm install -> a lot of errors!
give up.

See what I mean?!
How could we prohibit, that someone would do an update like he has done before? If he does, he WILL get frustrated!

**Comment by cprezzi** [comment]
I was able to install the exe version, which started the frontend, but that version has a lot of problems that was solved allready (Laser test, Play/Pause/Stop...). Which version is the exe from?

By the way: Opening a JPG is much slower.

**Comment by cprezzi** [comment]
Here is what I get with npm start:

cprez@CSWWS02 MINGW64 ~/git/LaserWeb/LaserWeb3 (master)
$ git fetch origin emblaser
remote: Counting objects: 71, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 71 (delta 38), reused 17 (delta 17), pack-reused 7
Unpacking objects: 100% (71/71), done.
From https://github.com/LaserWeb/LaserWeb3
 * branch            emblaser   -> FETCH_HEAD
   1e50630..44fe8b7  emblaser   -> origin/emblaser

cprez@CSWWS02 MINGW64 ~/git/LaserWeb/LaserWeb3 (master)
$ git checkout emblaser
Switched to branch 'emblaser'
Your branch is behind 'origin/emblaser' by 77 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

cprez@CSWWS02 MINGW64 ~/git/LaserWeb/LaserWeb3 (emblaser)
$ npm start

> @ start C:\Users\cprez\git\LaserWeb\LaserWeb3
> npm install && npm run copy && electron ./app

npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN optional dep failed, continuing 7zip-bin-mac@1.0.1
npm WARN optional dep failed, continuing 7zip-bin-linux@1.0.3

> serialport@4.0.6 install C:\Users\cprez\git\LaserWeb\LaserWeb3\node_modules\serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "C:\Users\cprez\git\LaserWeb\LaserWeb3\node_modules\serialport\build\Release\serialport.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> @ postinstall C:\Users\cprez\git\LaserWeb\LaserWeb3
> install-app-deps

Installing app dependencies for arch x64 to C:\Users\cprez\git\LaserWeb\LaserWeb3\app
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> serialport@4.0.6 install C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport
> node-pre-gyp install --fallback-to-build


C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport\build\Release )  else (node "" configure --fallback-to-build --module=C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport\build\Release )
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport\build\Release' (1)

Error output:
npm WARN package.json laserweb@3.254.0 No README data
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\cprez\\git\\LaserWeb\\LaserWeb3\\app\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\cprez\\git\\LaserWeb\\LaserWeb3\\app\\node_modules\\serialport\\build\\Release"
gyp ERR! cwd C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cprez\\git\\LaserWeb\\LaserWeb3\\app\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\cprez\git\LaserWeb\LaserWeb3\app\node_modules\serialport
node-pre-gyp ERR! node -v v4.6.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production" "--cache-min" "999999999"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! serialport@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@4.0.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cprez\git\LaserWeb\LaserWeb3\app\npm-debug.log

    at ChildProcess.<anonymous> (C:\Users\cprez\git\LaserWeb\LaserWeb3\node_modules\electron-builder\src\util\util.ts:135:14)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at spawn (C:\Users\cprez\git\LaserWeb\LaserWeb3\node_modules\electron-builder\src\util\util.ts:98:3)
    at installDependencies (C:\Users\cprez\git\LaserWeb\LaserWeb3\node_modules\electron-builder\src\yarn.ts:55:3)
    at C:\Users\cprez\git\LaserWeb\LaserWeb3\node_modules\electron-builder\src\yarn.ts:12:11
    at next (native)
From previous event:
    at installOrRebuild (C:\Users\cprez\git\LaserWeb\LaserWeb3\node_modules\electron-builder\out\yarn.js:33:21)
    at C:\Users\cprez\git\LaserWeb\LaserWeb3\node_modules\electron-builder\src\cli\install-app-deps.ts:28:2
    at next (native)
From previous event:
    at main (C:\Users\cprez\git\LaserWeb\LaserWeb3\node_modules\electron-builder\out\cli\install-app-deps.js:32:21)
    at Object.<anonymous> (C:\Users\cprez\git\LaserWeb\LaserWeb3\node_modules\electron-builder\out\cli\install-app-deps.js:72:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! @ postinstall: `install-app-deps`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the @ postinstall script 'install-app-deps'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-app-deps
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cprez\git\LaserWeb\LaserWeb3\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! @ start: `npm install && npm run copy && electron ./app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'npm install && npm run copy && electron ./app'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm run copy && electron ./app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\cprez\git\LaserWeb\LaserWeb3\npm-debug.log

cprez@CSWWS02 MINGW64 ~/git/LaserWeb/LaserWeb3 (emblaser)
$

**Comment by cprezzi** [comment]
I had to do a git pull (for the new emplaser stuff) and then run the npm start in a cmd window under admin rights to get through. Result: I get the same Version which is not usable (at least with Grbl).

By default, server-smoothie.js is started allways (in package.json) and there is no hint how to change that to grbl. There needs to be a Readme.txt at least, or a remark during start.

I quit for today...

**Comment by ghost** [comment]
Yeah i havent pulled over the grbl stuff yet (just enough to fix the merge
problems)  -  i only have a Smoothieboard with me.  Only flying home on the
9th dec...

**Comment by cprezzi** [comment]
Am I right, that the exe can also be made out of a branch? 
If true, then we should first merge master to emblaser insted of vice versa. 
Then test emblaser with all platforms with controllers.

PS: I have allways an Arduino Nano with Grbl with me ;) (much smaller than smoothie)

**Comment by ghost** [comment]
I did do a merge of master into Emblaser. Thats why my new DRO is in
there.  Weird that the merge didnt take the grbl stuff.  Maybe because of
later commits on emblaser side

**Comment by cprezzi** [comment]
Probably the problem is only, that server-smoothie is started (even after I changed package.json).

**Comment by ghost** [comment]
Probably.  I think perhaps best thing might be to implement that plan you
had of a single server.js that serves both firmwares.  That way only one to
start.  The additions to current server-*.js is just that small electron
section at the bottom

**Comment by ghost** [comment]
Going to close this PR 

I forked emblaser-electron to https://github.com/LaserWeb/LaserWeb3/tree/Electron-LW3 so I can play without breaking any more things. 

Sorry @cprezzi and @krolco 

Feel free to revert to last HEAD where it was all good (:

**Pull request closed without merging**
