### PR TITLE
Emblaser electron

### PR DESCRIPTION
**Pull request by krolco**

### CODE REVIEW

**Comment by jorgerobles** [comment]
So, Is this electron.github.io enabled? Would it run as a standalone app?

**Comment by jorgerobles** [comment]
Ok, I've seen #135 :)

**Comment by copet80** [comment]
@krolco Thanks! Yeah timezone + full-time job + kids make it even harder haha. But thanks for merging it. My bad for choosigg the wrong merge target.

@jorgerobles Yes the mac installer is ready. I'm still testing the installer on Windows, turns out to be more PITA. You can test it as well, but once the auto-update works, I'm hoping we can expose the compiled installers somewhere for everyone to download _fingers crossed_

**Comment by copet80** [comment]
@jorgerobles both the standalone app and the installer have been tested on Mac OSX and working for us, but not tested on Windows yet.

**Comment by jorgerobles** [comment]
@copet80  Thanks, but sorry, is there any .dmg or so?

**Comment by anthonytvamp** [comment]
No not yet as I'm still testing it as it's still very early phase. Having said that though, if you can't wait for our .dmg, you should be able to build the .dmg, or at the very list the .app yourself if you have Mac OSX.

**Comment by cojarbi** [comment]
I'm on OSX how do I package it? 

AY

On Monday, October 10, 2016 Anthony Tambrin notifications@github.com wrote:

No not yet as I'm still testing it as it's still very early phase. Having said that though, if you can't wait for our .dmg, you should be able to build the .dmg, or at the very list the .app yourself if you have Mac OSX.

**Comment by anthonytvamp** [comment]
@cojarbi 
1. Go to the project folder
2. `npm install`
3. `npm run dist`
4. Find the .dmg file created in dist folder

Note: if you just want to create .app without creating .dmg, run `npm run pack` instead. Alternatively if you just want to be able to run LaserWeb in electron without creating an app or installer, run `npm start`.

If that doesn't work just try installing electron and electron-debug globally:
1. `npm install -g electron`
2. `npm install -g electron-debug`

**Comment by copet80** [comment]
@jorgerobles 
No not yet as I'm still testing it as it's still very early phase. Having said that though, if you can't wait for our .dmg, you should be able to build the .dmg, or at the very list the .app yourself if you have Mac OSX.

@cojarbi 
1. Go to the project folder
2. `npm install`
3. `npm run dist`
4. Find the .dmg file created in dist folder

Note: if you just want to create .app without creating .dmg, run `npm run pack` instead. Alternatively if you just want to be able to run LaserWeb in electron without creating an app or installer, run `npm start`.

If that doesn't work just try installing electron and electron-debug globally:
1. `npm install -g electron`
2. `npm install -g electron-debug`

**Comment by cojarbi** [comment]
I can also help test windows if you need that

**Comment by copet80** [comment]
@cojarbi That'd be great :) I'm having my own fair share of PITA moment right now with Windows. I'm keen to see if you'd have a (hopefully) better experience with it.

**Comment by cojarbi** [comment]
Ill do talk tonight, what the build process for Windows or is it the same?

**Comment by jorgerobles** [comment]
Thanks! I will try :)

**Comment by cojarbi** [comment]
If starting is the same in windows, then i keep getting the following 

C:\laserweb3>npm start

> @ start C:\laserweb3
> npm install && npm run copy && electron ./app

npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN engine xmlbuilder@8.2.2: wanted: {"node":">=4.0"} (current: {"node":"0.
12.7","npm":"2.11.3"})
npm WARN optional dep failed, continuing 7zip-bin-osx@1.0.0
npm WARN optional dep failed, continuing 7zip-bin-linux@1.0.2

> electron@1.4.1 postinstall C:\laserweb3\node_modules\electron
> node install.js

Downloading SHASUMS256.txt
[============================================>] 100.0% of 2.85 kB (2.85 kB/s)

> serialport@4.0.3 install C:\laserweb3\node_modules\serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "C:\laserweb3\node_modules\serialport\build\Release\serial
port.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> @ postinstall C:\laserweb3
> install-app-deps

C:\laserweb3\node_modules\electron-builder\out\install-app-deps.js:5
const util_1 = require("./util/util");
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (
x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! @ postinstall: `install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ postinstall script 'install-app-deps'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-app-deps
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\laserweb3\npm-debug.log

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (
x86)\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! @ start: `npm install && npm run copy && electron ./app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'npm install && npm run copy && electron .
/app'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm run copy && electron ./app
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\laserweb3\npm-debug.log

C:\laserweb3>

**Comment by krolco** [comment]
@copet80 No problem! :)

**Comment by ghost** [comment]
@cojarbi looks like you are on node 0.12.  We moved up to node 4 (:

**Comment by cojarbi** [comment]
Yeah my bad there, mutiple VM's here and that one was outdated. Still runninng npm on the Emblaser branch on windows gives me the following
[Emblaser.txt](https://github.com/openhardwarecoza/LaserWeb3/files/521782/Emblaser.txt)

**Comment by copet80** [comment]
@cojarbi it looks like it's complaining you don't have python installed. Try installing python 2.7.x.

**Comment by copet80** [comment]
I'm still playing around with electron-rebuild and trying to resolve the issue with serialport that gives me the "Error: A dynamic link library (DLL) initialization routine failed.".

**Comment by ghost** [comment]
I suspect you'll need to setup a windows build environment and rebuild
node-serialport against electron.  They provide prebuilt binaries for Node
only.

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
and
https://github.com/EmergingTechnologyAdvisors/node-serialport#installation-special-cases

**Comment by ghost** [comment]
@copet80 ok so back to the Windows issues..., so I installed https://github.com/felixrieseberg/windows-build-tools

Next I went into the Emblaser branch and ran npm install; npm start.

App started without issue... Can you elaborate where we are with https://github.com/LaserWeb/LaserWeb3/pull/154#issuecomment-252751335

And a full update on when we can make Electron the primary delivery mechanism?

**Pull request merged**
