### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by KotieSmit**
Added Dockerfile for those wanting to use docker as part of their dev environment.

### CODE REVIEW

**Comment by ghost** [comment]
Kotie Smit,  any chance you have a brother name Willie?  (:

**Comment by jorgerobles** [comment]
Cool. Could be done for LW4 too :)

**Comment by ghost** [comment]
(: yeah dont do too much to LW3...  We are very close to releasing LW4 and deprecating LW3

**Comment by ghost** [comment]
@KotieSmit  (; still curious, I do think I may know you? https://github.com/LaserWeb/LaserWeb3/pull/224#issuecomment-275338647

**Pull request merged**
